### ISSUE TITLE
revpool type

### ISSUE THREAD

**Issue by bkamins** [JuliaData/PooledArrays.jl#14]
Looking at the code maybe `revpool` could be defined as `Vector{T}`. I do not see any place where we take advantage of the  fact that it is a `Dict`.

@nalimilan - this would influence the performance of https://github.com/JuliaData/DataFrames.jl/pull/1703 I think.

**Comment by nalimilan** [comment]
See https://github.com/JuliaComputing/PooledArrays.jl/pull/5.
