### ISSUE TITLE
What is the relation to CategoricalArrays?

### ISSUE THREAD

**Issue by davidanthoff** [JuliaData/PooledArrays.jl#2]
https://github.com/JuliaData/CategoricalArrays.jl

Do they both try to do the same thing, i.e. replace ``PooledDataArray``?

cc @nalimilan.

**Comment by JeffBezanson** [comment]
A PooledArray behaves exactly like a normal array, with no behavior related to categorical variables or missing data. The pooled representation is only for memory efficiency and nothing else. The current implementation also assumes the element type has a total order, to allow a fast `sortperm`.

If the categorical value code can be factored out of CategoricalArrays, then it's possible this package could be merged with its array type.

**Comment by xiaodaigh** [comment]
@JeffBezanson does that mean that PooledArray does not support Nulls.Null?

**Comment by nalimilan** [comment]
@xiaodaigh PooledArrays shouldn't need to do anything special to support `null`, it can work just like any other value. Do you have a use case in mind?

**Comment by bkamins** [comment]
can this be closed?
