### ISSUE TITLE
Change the default type of ref

### ISSUE THREAD

**Issue by bkamins** [JuliaData/PooledArrays.jl#39]
Currently we have:
```
julia> x = PooledArray(zeros(Int, 10^6));
julia> copyto!(x, 1:10^6);
ERROR: You're using a PooledArray with ref type UInt8, which can only hold 255 values,
and you just tried to add the 256th reference.  Please change the ref type
to a larger int type, or use the default ref type (UInt32).
```
I think we should use `UInt32` as the default as in practice limiting up to 255 levels by default is a small value. If someone wants such a limit to save memory I would have it as an opt-in rather than the default.

@quinnj - what does CSV.jl use as a default?

**Comment by quinnj** [comment]
CSV.jl uses UInt32; I agree we should just make UInt32 the default here
