### ISSUE TITLE
PooledArrays.jl 0.6 release

### ISSUE THREAD

**Issue by bkamins** [JuliaData/PooledArrays.jl#45]
There has been a year since the last patch release of PooledArrays.jl I think with the changes we have we should aim to make a 0.6 release. We have some important breaking changes already on master + several issues/PRs open.

I think it would be good to make a release. I will comment on the open issues/PRs to make a decision if we want to include them or not in 0.6 release.

CC @nalimilan + @quinnj

**Comment by quinnj** [comment]
We should tag 1.0. I really want all JuliaData registered packages to have 1.0 tagged.

**Comment by nalimilan** [comment]
Why not, but before doing that we should review the API to ensure we're mostly OK with it.

**Comment by bkamins** [comment]
This is exactly what I intended.

**Comment by nalimilan** [comment]
Too late now.
