### ISSUE TITLE
Disallow mutable eltype in PooledArray

### ISSUE THREAD

**Issue by bkamins** [JuliaData/PooledArrays.jl#51]
I think we should disallow allowing mutable elements of `PooledArray`.

The reason of this proposal is the following problem:
```
julia> x = PooledArray([[1]])
1-element PooledArray{Array{Int64,1},UInt8,1,Array{UInt8,1}}:
 [1]

julia> push!(x[1], 2)
2-element Array{Int64,1}:
 1
 2

julia> x.invpool
Dict{Array{Int64,1},UInt8} with 1 entry:
  [1, 2] => 0x01

julia> x.invpool[[1,2]]
ERROR: KeyError: key [1, 2] not found
```

Alternatively we should change how `invpool` is handled if mutable objects are stored in `PooledArray` or explicitly warn that it is not allowed to mutate them.

**Comment by nalimilan** [comment]
It would indeed be safer. As an alternative maybe we could use an `ObjectIdDict` for mutable objects, but that probably more work than it's worth.

**Comment by bkamins** [comment]
Then, given we have tagged PooledArrays.jl as 1.0, maybe we just add a warning not to mutate the stored objects?

**Comment by quinnj** [comment]
Hmmm, in Arrow.jl, you're allowed to dict-encode anything you want, but then again, everything is assumed immutable, so this isn't really an issue. On the one hand, no one has ever brought this up, so I wonder if people tend to not do this anyway, or just don't run into it. A warning might be fine, just as a way to see if anybody might be doing some mutating unintentionally. But I think we should keep allowing mutable eltypes for now.
