### ISSUE TITLE
Auto bumping ref type to the next larger int type

### ISSUE THREAD

**Issue by tk3369** [JuliaData/PooledArrays.jl#6]
Hi there.  Great package!  

Is there any reason not to make it smarter by automatically bumping to the next larger int type?  I can do that manually but thought it could be a nice feature.

```
julia> x = PooledArray(fill(1,300));

julia> typeof(x)
PooledArrays.PooledArray{Int64,UInt8,1,Array{UInt8,1}}

julia> x[1:300] = 1:300
ERROR: You're using a PooledArray with ref type UInt8, which can only hold 255 values,
and you just tried to add the 256th reference.  Please change the ref type
to a larger int type, or use the default ref type (UInt32).
```

**Comment by shashi** [comment]
This is not possible since we would have to change the type of `x`...

**Comment by bkamins** [comment]
Can this be closed?

**Comment by tk3369** [comment]
I’m ok if there’s no interest.

**Comment by bkamins** [comment]
I think what @shashi says that that this size is a part of type parametrization of the `PooledArray` type.

**Comment by tk3369** [comment]
That’s true 😅
